name: flutter_customs
description: new package project that create customs to make it easier for developers.
version: 0.0.28
homepage: https://github.com/Kadiex/flutter_customs
repository: https://github.com/Kadiex/flutter_customs

topics:
  - customphoneform
  - customsvg
  - custombottomsheet
  - custombutton
  - customcheckbox

funding:
  - https://buymeacoffee.com/alrehila

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.1
  vector_graphics: ^1.1.11+1
  vector_graphics_codec: ^1.1.11+1
  vector_graphics_compiler: ^1.1.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# screenshots:
#   - description: 'This screenshot shows the transformation of a number of bytes 
#   to a human-readable expression.'
#     path: path/to/image/in/package/500x500.webp
#   - description: 'This screenshot shows a stack trace returning a human-readable
#   representation.'
#     path: path/to/image/in/package.png

flutter:

  assets:
    - assets/countries/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
